SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";




CREATE TABLE IF NOT EXISTS player (
  ID_PLAYER int(11) NOT NULL AUTO_INCREMENT,
  LOGIN varchar(50) COLLATE utf8_polish_ci NOT NULL,
  PASSWORD varchar(50) COLLATE utf8_polish_ci NOT NULL,
  PRIMARY KEY(ID_PLAYER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;



CREATE TABLE IF NOT EXISTS game (
  ID_GAME int(11) NOT NULL AUTO_INCREMENT,
  ID_PLAYER1 int(11) NOT NULL,
  ID_PLAYER2 int(11) NOT NULL,
  DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ID_WINNER int(11),
	PRIMARY KEY(ID_GAME),
	FOREIGN KEY (ID_PLAYER1) REFERENCES player(ID_PLAYER) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY (ID_PLAYER2) REFERENCES player(ID_PLAYER) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY (ID_WINNER) REFERENCES player(ID_PLAYER) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

CREATE TABLE IF NOT EXISTS progress (
	ID_PROGRESS int(11) NOT NULL AUTO_INCREMENT,
	ID_GAME int(11) NOT NULL,
	TURE int(11) NOT NULL,
	ID_PLAYER int(11) NOT NULL,
	CORD varchar(4) COLLATE utf8_polish_ci NOT NULL,
	STATUS tinyint(1) NOT NULL,
	PRIMARY KEY(ID_PROGRESS),
	FOREIGN KEY (ID_GAME) REFERENCES game(ID_GAME) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY (ID_PLAYER) REFERENCES player(ID_PLAYER) ON DELETE RESTRICT ON UPDATE RESTRICT	
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;